gitlab:
  ports:
    ssh: 22
    http: 80
    https: 443
gitlabrunner:
  replicas: 2
config:
  gitlab:
    file: ./gitlab-config/gitlab.rb
secrets:
  rootpassword:
    file: ./secrets/root_password.txt
