version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:12.3.4-ce.0
    ports:
      - "${gitlab.ports.ssh}:22"
      - "${gitlab.ports.http}:80"
      - "${gitlab.ports.https}:443"
    volumes:
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab-root-password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: ${gitlabrunner.replicas}
configs:
  gitlab:
    file: ${config.gitlab.file}
secrets:
  gitlab-root-password:
    file: ${secrets.rootpassword.file}
